# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quackmessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'quackmessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12quackmessage.proto\"2\n\x0cLoginMessage\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"2\n\x0bLoginResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nauth_token\x18\x02 \x01(\t\"#\n\x12VerifyEmailMessage\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"*\n\x15VerificationEmailSent\x12\x11\n\temailSent\x18\x01 \x01(\x08\"\'\n\x17VerificationCodeMessage\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\"+\n\x17VerificationCodeMatches\x12\x10\n\x08verified\x18\x01 \x01(\x08\"7\n\x11\x43reateUserMessage\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"#\n\x10\x43reateUserResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xf2\x01\n\x10QuackMessageAuth\x12&\n\x05Login\x12\r.LoginMessage\x1a\x0c.LoginResult\"\x00\x12\x35\n\nCreateUser\x12\x12.CreateUserMessage\x1a\x11.CreateUserResult\"\x00\x12<\n\x0bVerifyEmail\x12\x13.VerifyEmailMessage\x1a\x16.VerificationEmailSent\"\x00\x12\x41\n\tCheckCode\x12\x18.VerificationCodeMessage\x1a\x18.VerificationCodeMatches\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quackmessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINMESSAGE']._serialized_start=22
  _globals['_LOGINMESSAGE']._serialized_end=72
  _globals['_LOGINRESULT']._serialized_start=74
  _globals['_LOGINRESULT']._serialized_end=124
  _globals['_VERIFYEMAILMESSAGE']._serialized_start=126
  _globals['_VERIFYEMAILMESSAGE']._serialized_end=161
  _globals['_VERIFICATIONEMAILSENT']._serialized_start=163
  _globals['_VERIFICATIONEMAILSENT']._serialized_end=205
  _globals['_VERIFICATIONCODEMESSAGE']._serialized_start=207
  _globals['_VERIFICATIONCODEMESSAGE']._serialized_end=246
  _globals['_VERIFICATIONCODEMATCHES']._serialized_start=248
  _globals['_VERIFICATIONCODEMATCHES']._serialized_end=291
  _globals['_CREATEUSERMESSAGE']._serialized_start=293
  _globals['_CREATEUSERMESSAGE']._serialized_end=348
  _globals['_CREATEUSERRESULT']._serialized_start=350
  _globals['_CREATEUSERRESULT']._serialized_end=385
  _globals['_QUACKMESSAGEAUTH']._serialized_start=388
  _globals['_QUACKMESSAGEAUTH']._serialized_end=630
# @@protoc_insertion_point(module_scope)
