# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import quackmessage_pb2 as quackmessage__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in quackmessage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuackMessageAuthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/QuackMessageAuth/Login',
                request_serializer=quackmessage__pb2.LoginMessage.SerializeToString,
                response_deserializer=quackmessage__pb2.LoginResult.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/QuackMessageAuth/CreateUser',
                request_serializer=quackmessage__pb2.CreateUserMessage.SerializeToString,
                response_deserializer=quackmessage__pb2.CreateUserResult.FromString,
                _registered_method=True)
        self.VerifyEmail = channel.unary_unary(
                '/QuackMessageAuth/VerifyEmail',
                request_serializer=quackmessage__pb2.VerifyEmailMessage.SerializeToString,
                response_deserializer=quackmessage__pb2.VerificationEmailSent.FromString,
                _registered_method=True)
        self.CheckCode = channel.unary_unary(
                '/QuackMessageAuth/CheckCode',
                request_serializer=quackmessage__pb2.VerificationCodeMessage.SerializeToString,
                response_deserializer=quackmessage__pb2.VerificationCodeMatches.FromString,
                _registered_method=True)


class QuackMessageAuthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuackMessageAuthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=quackmessage__pb2.LoginMessage.FromString,
                    response_serializer=quackmessage__pb2.LoginResult.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=quackmessage__pb2.CreateUserMessage.FromString,
                    response_serializer=quackmessage__pb2.CreateUserResult.SerializeToString,
            ),
            'VerifyEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyEmail,
                    request_deserializer=quackmessage__pb2.VerifyEmailMessage.FromString,
                    response_serializer=quackmessage__pb2.VerificationEmailSent.SerializeToString,
            ),
            'CheckCode': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckCode,
                    request_deserializer=quackmessage__pb2.VerificationCodeMessage.FromString,
                    response_serializer=quackmessage__pb2.VerificationCodeMatches.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'QuackMessageAuth', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('QuackMessageAuth', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuackMessageAuth(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/QuackMessageAuth/Login',
            quackmessage__pb2.LoginMessage.SerializeToString,
            quackmessage__pb2.LoginResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/QuackMessageAuth/CreateUser',
            quackmessage__pb2.CreateUserMessage.SerializeToString,
            quackmessage__pb2.CreateUserResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/QuackMessageAuth/VerifyEmail',
            quackmessage__pb2.VerifyEmailMessage.SerializeToString,
            quackmessage__pb2.VerificationEmailSent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/QuackMessageAuth/CheckCode',
            quackmessage__pb2.VerificationCodeMessage.SerializeToString,
            quackmessage__pb2.VerificationCodeMatches.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
