# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x1a\x1fgoogle/protobuf/timestamp.proto\")\n\x16receiveMessagesRequest\x12\x0f\n\x07request\x18\x01 \x01(\x08\"\xa9\x01\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\tmessageId\x18\x04 \x01(\x05\x12+\n\x07sent_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07seen_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"L\n\nupdateSeen\x12\x11\n\tmessageId\x18\x01 \x01(\x05\x12+\n\x07seen_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"#\n\x10updateSeenResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\"?\n\x11sendMessageResult\x12\x16\n\x0esendSuccessful\x18\x01 \x01(\x08\x12\x12\n\nmessage_id\x18\x02 \x01(\x05\"\"\n\x0f\x63ontactsRequest\x12\x0f\n\x07request\x18\x01 \x01(\x08\"\x17\n\x07\x63ontact\x12\x0c\n\x04name\x18\x01 \x01(\t\")\n\x0b\x63ontactList\x12\x1a\n\x08\x63ontacts\x18\x01 \x03(\x0b\x32\x08.contact2\xd7\x01\n\x08Messager\x12:\n\x11subscribeMessages\x12\x17.receiveMessagesRequest\x1a\x08.Message\"\x00\x30\x01\x12-\n\x0bsendMessage\x12\x08.Message\x1a\x12.sendMessageResult\"\x00\x12/\n\x0bgetContacts\x12\x10.contactsRequest\x1a\x0c.contactList\"\x00\x12/\n\x0bmessageSeen\x12\x0b.updateSeen\x1a\x11.updateSeenResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECEIVEMESSAGESREQUEST']._serialized_start=50
  _globals['_RECEIVEMESSAGESREQUEST']._serialized_end=91
  _globals['_MESSAGE']._serialized_start=94
  _globals['_MESSAGE']._serialized_end=263
  _globals['_UPDATESEEN']._serialized_start=265
  _globals['_UPDATESEEN']._serialized_end=341
  _globals['_UPDATESEENRESULT']._serialized_start=343
  _globals['_UPDATESEENRESULT']._serialized_end=378
  _globals['_SENDMESSAGERESULT']._serialized_start=380
  _globals['_SENDMESSAGERESULT']._serialized_end=443
  _globals['_CONTACTSREQUEST']._serialized_start=445
  _globals['_CONTACTSREQUEST']._serialized_end=479
  _globals['_CONTACT']._serialized_start=481
  _globals['_CONTACT']._serialized_end=504
  _globals['_CONTACTLIST']._serialized_start=506
  _globals['_CONTACTLIST']._serialized_end=547
  _globals['_MESSAGER']._serialized_start=550
  _globals['_MESSAGER']._serialized_end=765
# @@protoc_insertion_point(module_scope)
