### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Quackmessage_desktop)
add_subdirectory(Quackmessage_desktopContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Quackmessage_desktopplugin
    Quackmessage_desktopContentplugin
    QtQuickDesignerComponents)